import type { Metadata } from "next";
import "./globals.css";
import Signature from "@/components/Signature";



export const metadata: Metadata = {
  title: "Your Own QR Generator",
  description: "Generated by Insomniac",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Signature/>
      </body>
    </html>
  );
}
