import type { Metadata } from "next";
import "./globals.css";
import Signature from "@/components/Signature";
import Navbar from "@/components/Navbar";



export const metadata: Metadata = {
  title: "Your Own QR Generator",
  description: "Generated by Insomniac",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ background: "linear-gradient(-225deg, #FFFEFF 0%, #D7FFFE 100%)" }}>
        <Navbar/>
        {children}
        <Signature/>
      </body>
    </html>
  );
}
